const SET_TITLE = "SET_TITLES";
const SET_RESINFO = "SET_RESINFOS";
const SET_ISCHILDSHOW = "SET_ISCHILDSHOWS";
const SET_ISGOSHOW = "SET_ISGOSHOW";

const SET_TOKEN = "SET_TOKEN"; // TOKEN设置
export  {
  SET_TITLE,
  SET_RESINFO,
  SET_ISCHILDSHOW,
  SET_ISGOSHOW,
  SET_TOKEN
};
